apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-chart
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
